apiVersion: v1
kind: Service
metadata:
  labels:
    tier: utils
  name: uk-service
spec:
  type: LoadBalancer
  selector:
    tier: updatekate
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: uk-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: updatekate
    spec:
      restartPolicy: Always
      containers:
      - name: updatekate
        env:
        - name: UK_DEPLOYMENT
          value: ec-deployment
        - name: UK_NAMESPACE
          value: ec
        - name: UK_WEBHOOK
          value: http://192.168.1.1/webhook
        - name: UK_REPO
          value: quay.io/boundlessgeo/geoserver-ec
        image: tingold/updatekate:0.0.16
        ports:
        - containerPort: 8888
        securityContext:
          privileged: true